[package]
name = "distinst"
description = "Distribution Installer Backend"
version = "0.3.0"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
build = "build.rs"

[lib]
crate-type = ["dylib"]

[build-dependencies]
cbindgen = "0.3"

[dependencies]
clap = "=2.26.0"
libc = "0.2"
libparted = { git = "https://github.com/system76/libparted.git" }
log = "0.3"
pbr = "1.0"
tempdir = "0.3"
