[package]
name = "distinst"
description = "Distribution Installer Backend"
version = "0.2.0"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
build = "build.rs"

[lib]
name = "distinst"
crate-type = ["lib", "dylib"]

[build-dependencies]
moz-cheddar = "0.4.0"

[dependencies]
"clap" = "2.26"
"libc" = "0.2"
"log" = "0.3"
"pbr" = "1.0"
"tempdir" = "0.3"
#TODO "libparted" = { "git" = "https://github.com/system76/libparted.git" }
