[package]
name = "distinst"
version = "0.5.0"
description = "Distribution Installer Backend"
repository = "https://github.com/pop-os/distinst"
categories = ["os::unix-apis"]
keywords = ["linux", "distribution", "installer"]
authors = [
    "Jeremy Soller <jackpot51@gmail.com>",
    "Michael Aaron Murphy <michael@system76.com>"
]
license = "LGPL-3.0"
readme = "README.md"

[workspace]
members = [
    "cli",
    "ffi",
    "crates/bootloader",
    "crates/chroot",
    "crates/disks",
    "crates/disk-ops",
    "crates/disk-types",
    "crates/envfile",
    "crates/external",
    "crates/fstab-generate",
    "crates/hostname-validator",
    "crates/locales",
    "crates/logind-dbus",
    "crates/os-detect",
    "crates/os-release",
    "crates/proc-modules",
    "crates/proc-mounts",
    "crates/squashfs",
    "crates/utils",
]

[lib]
name = "distinst"
crate-type = ["lib"]

[dev-dependencies]
pbr = "1.0.1"

[dependencies]
cascade = "0.1.2"
dirs = "1.0.3"
disk-types = { path = "crates/disk-types" }
distinst-bootloader = { path = "crates/bootloader" }
distinst-chroot = { path = "crates/chroot" }
distinst-disks = { path = "crates/disks" }
distinst-external-commands = { path = "crates/external" }
distinst-locale-support = { path = "crates/locales" }
distinst-squashfs = { path = "crates/squashfs" }
distinst-utils = { path = "crates/utils" }
envfile = { path = "crates/envfile" }
fern = "0.5.6"
fstab-generate = { path = "crates/fstab-generate" }
hostname-validator = { path = "crates/hostname-validator" }
itertools = "0.7.8"
libc = "0.2.43"
libparted = "0.1.3"
log = "0.4.5"
logind-dbus = { path = "crates/logind-dbus" }
os-detect = { path = "crates/os-detect" }
os-release = { path = "crates/os-release" }
partition-identity = "0.1.2"
proc-modules = { path = "crates/proc-modules" }
proc-mounts = { path = "crates/proc-mounts" }
raw-cpuid = "5.0.0"
rayon = "1.0.2"
sys-mount = "1.0.3"
tempdir = "0.3.7"

[dependencies.failure]
version = "0.1.2"
default-features = false
features = ["derive"]

[dependencies.failure_derive]
version = "0.1.2"

[profile.release]
debug = true
