[package]
name = "distinst"
version = "0.3.2"
description = "Distribution Installer Backend"
repository = "https://github.com/pop-os/distinst"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
license = "LGPL-3.0"
readme = "README.md"

[lib]
name = "distinst"
crate-type = ["lib"]

[dependencies]
clap = "=2.26.0"
libc = "0.2"
libparted = "0.1.2"
log = "0.3"
pbr = "1.0"
tempdir = "0.3"
itertools = "0.7.6"

[dependencies.failure]
version = "0.1.1"
default-features = false
features = ["derive"]

[dependencies.failure_derive]
version = "0.1.1"
