[package]
name = "distinst"
version = "0.3.0"
description = "Distribution Installer Backend"
repository = "https://github.com/pop-os/distinst"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
license = "LGPL-3.0"
build = "build.rs"
readme = "README.md"

[lib]
name = "distinst"
crate-type = ["lib", "dylib"]

[build-dependencies]
cbindgen = "0.3"

[dependencies]
clap = "=2.26.0"
libc = "0.2"
libparted = "0.1"
log = "0.3"
pbr = "1.0"
tempdir = "0.3"
failure = "0.1.1"
failure_derive = "0.1.1"
