[package]
name = "distinst"
description = "Distribution Installer Backend"
version = "0.1.0"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
build = "build.rs"

[lib]
name = "distinst"
crate-type = ["lib", "dylib"]

[build-dependencies]
moz-cheddar = "0.4.0"

[dependencies]
"libc" = "0.2"
"libparted" = { "git" = "https://github.com/system76/libparted.git" }
