[package]
name = "distinst_cli"
version = "0.3.2"
description = "Distribution Installer Backend"
repository = "https://github.com/pop-os/distinst"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
license = "LGPL-3.0"
readme = "README.md"

[[bin]]
name = "distinst"
path = "src/main.rs"

[dependencies]
clap = "=2.26.0"
distinst = { path = ".." }
libc = "0.2"
pbr = "1.0"

[dependencies.failure]
version = "0.1.1"
default-features = false
features = ["derive"]

[dependencies.failure_derive]
version = "0.1.1"
