[package]
name = "distinst-disks"
version = "0.1.0"
authors = ["Jeremy Soller <jackpot51@gmail.com>", "Michael Aaron Murphy <mmstickman@gmail.com>"]
description = "Probe and manipulate block devices"

[dependencies]
bitflags = "1.0.4"
derive-new = "0.5.5"
disk-ops = { path = "../disk-ops" }
disk-types = { path = "../disk-types" }
distinst-bootloader = { path = "../bootloader" }
distinst-external-commands = { path = "../external" }
distinst-utils = { path = "../utils" }
envfile = { path = "../envfile" }
failure = "0.1.3"
failure_derive = "0.1.3"
fstab-generate = { path = "../fstab-generate" }
itertools = "0.7.8"
libc = "0.2.43"
libparted = "0.1.3"
log = "0.4.5"
os-detect = { path = "../os-detect" }
partition-identity = { git = "https://github.com/pop-os/partition-identity" }
proc-mounts = { path = "../proc-mounts" }
rand = "0.5.5"
rayon = "1.0.2"
sys-mount = "1.0.3"
sysfs-class = { git = "https://github.com/pop-os/sysfs-class" }
tempdir = "0.3.7"
