[package]
name = "distinst-chroot"
version = "0.1.0"
authors = ["Jeremy Soller <jackpot51@gmail.com>", "Michael Aaron Murphy <mmstickman@gmail.com>"]

[dependencies]
sys-mount = "1.0.3"
cascade = "0.1.2"
log = "0.4.5"
